# Generated by Django 5.1.2 on 2025-02-04 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_feedback"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="feedback",
            new_name="feedback_model",
        ),
    ]
