# Generated by Django 5.1.2 on 2025-03-05 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_data_otp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='otp',
        ),
    ]
