# Generated by Django 5.1.2 on 2025-04-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_seed'),
    ]

    operations = [
        migrations.AddField(
            model_name='seed',
            name='wikipedia_link',
            field=models.URLField(default=4),
            preserve_default=False,
        ),
    ]
