# Generated by Django 5.1.2 on 2025-04-19 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_seed_wikipedia_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('seed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.seed')),
            ],
        ),
    ]
