# Generated by Django 5.1.2 on 2025-04-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_percent', models.FloatField()),
                ('min_value', models.FloatField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
