# Generated by Django 5.1.2 on 2025-04-20 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_coupon_user_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_coupon',
            name='status',
        ),
    ]
