# Generated by Django 5.1.2 on 2025-04-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_solarpanelcontent_delete_order_delete_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='modernday_tech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='solar_images/')),
                ('link', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
